### ISSUE TITLE
Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by strikeru97** [spacemeowx2/slp-server-rust#11]
Running v2.0.0-rust.alpha.6, relase "slp-server-rust-linux-amd64"
System OS: Ubuntu 18.04 LTS Server on i7 920, Alpha 5 works perfect.
xxx@li7:~/rustserver$ ./slp-server-rust-linux-amd64.alpha6
[2020-04-12T12:15:06Z INFO  slp_server_rust] Listening on 0.0.0.0:11451
Ws error: Websocket error: WebSocket protocol error: Connection reset without closing handshake
Ws error: Websocket error: WebSocket protocol error: Connection reset without closing handshake
Ws error: Websocket error: IO error: Connection reset by peer (os error 104)

**Comment by spacemeowx2** [comment]
It could be safe to ignore. And shouldn't appear on latest version
