### ISSUE TITLE
Where i can get the token, to perfom graphql queries?

### ISSUE THREAD

**Issue by EsteveSegura** [spacemeowx2/slp-server-rust#14]
Im trying to perform this query
`
{
  trafficInfo(token:"blablabla"){
    upload
  }
}
`

Obviusly is deneid, beacause the token is wrong... Where i can find this token?
Thank you.

**Comment by igromanru** [comment]
I was recently going through the code and if I see it right, you have to set the token by yourself first.  
The parameter for the server to start with token should be like this:  
`./slp-server-rust-linux-amd64 --admin_token=(something to use as a token)`
