### ISSUE TITLE
Custom Build Failed

### ISSUE THREAD

**Issue by t0g3pii** [spacemeowx2/slp-server-rust#2]
`error: failed to run custom build command for `slp-server-rust v2.0.0-rust.alpha.3 (/root/slp-server-rust-master)`

Caused by:
  process didn't exit successfully: `/root/slp-server-rust-master/target/release/build/slp-server-rust-4dd1cb61801f6938/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed`

Happened when Updating from alpha1 to alpha3 and on a Fresh Install.

**Comment by spacemeowx2** [comment]
it happend because build.rs cannot run `git` command. Make sure you have `git` installed. The `GIT_HASH` will show when you run `--version`. It helps when reporting bugs.

Fixed by set a default of `GIT_HASH`

**Comment by t0g3pii** [comment]
(You should write in the ReadMe.md to avoid more Issues from others)
Thank you for the info!
